# Generated by Django 3.0 on 2025-04-18 22:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20250418_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedorder',
            name='books',
        ),
        migrations.AddField(
            model_name='completedorder',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='completedorder',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
    ]
