# Generated by Django 3.0 on 2025-04-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20250419_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedorder',
            name='books',
            field=models.ManyToManyField(to='books.Book'),
        ),
    ]
